### ISSUE TITLE
Change NEEDED !!

### ISSUE THREAD

**Issue by maddxyz** [ukarroum/ZZBrain#1]
Change this Line : `\usepackage[lmargin=3.81cm,tmargin=2.54cm,rmargin=2.54cm,bmargin=2.52cm]{geometry}`
With this one : `\usepackage[lmargin=1.9cm,tmargin=2.54cm,rmargin=2.0cm,bmargin=2.52cm]{geometry}`

**Comment by maddxyz** [comment]
@ukarroum

**Comment by ukarroum** [comment]
Done
